default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: serious_todo_development

test:
  <<: *default
  database: serious_todo_test

production:
  <<: *default
  database: serious_todo_production
  url: <%= ENV["DATABASE_URL"] %>
