development:
  secret_key_base: a66d6b08c8c60998e28fdf6a701120bb913dd622555a5cd5689230ec526b487ba98cf10b6e05110908cca526e6e30c7af8b83e8de26d14e6dacaf7ae1a02765e
  domain_name: localhost
  state: 9jm9ziaurod3jajfkyi0
  todoist_id: 47e2c45daa5f451188e6dbc2a99ca37c
  todoist_secret: 4a230978126440688f2687bfa45f6c5a
  stripe_key: pk_test_LV7yGhsCmUXd12JUn8KTAYwR
  stripe_secret: sk_test_QhXOFupZG5silwaylKSi6zoV
  segment_key: L8FrLGzM3A1sDif60AaxdpeziIxUEOeC

test:
  secret_key_base: 9aadaaf76ed125df26e2757b8e9fbc3f515585a05f60ea3f6fc5f2fa2e21502ba78a8b027d1aa57f1870020c4ecd70aa2805755881b99778efff5315662a5f07
  domain_name: locahost
  segment_key: 1234567456qw

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailer_address: <%= ENV["SENDGRID_ADDRESS"] %>
  mailer_username: <%= ENV["SENDGRID_USERNAME"] %>
  mailer_password: <%= ENV["SENDGRID_PASSWORD"] %>
  state: <%= ENV["STATE"] %>
  todoist_id: <%= ENV["TODOIST_ID"] %>
  todoist_secret: <%= ENV["TODOIST_SECRET"] %>
  stripe_key: <%= ENV["STRIPE_KEY"] %>
  stripe_secret: <%= ENV["STRIPE_SECRET"] %>
  segment_key: <%= ENV["SEGMENT_KEY"] %>
