development:
  secret_key_base: a66d6b08c8c60998e28fdf6a701120bb913dd622555a5cd5689230ec526b487ba98cf10b6e05110908cca526e6e30c7af8b83e8de26d14e6dacaf7ae1a02765e
  domain_name: localhost
  state: 9jm9ziaurod3jajfkyi0

test:
  secret_key_base: 9aadaaf76ed125df26e2757b8e9fbc3f515585a05f60ea3f6fc5f2fa2e21502ba78a8b027d1aa57f1870020c4ecd70aa2805755881b99778efff5315662a5f07
  domain_name: locahost
  state: nj6lqhpysjvvfkpm6ohs

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailer_address: <%= ENV["SENDGRID_ADDRESS"] %>
  mailer_username: <%= ENV["SENDGRID_USERNAME"] %>
  mailer_password: <%= ENV["SENDGRID_PASSWORD"] %>
  state: 0850njzz56nihr5zmo78
